CREATE TABLE users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    family_id INT,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    profile TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
